name: Validate Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Actions
      uses: actions/checkout@v4
    - name: Set up Docker and Configure Arch Linux
      run: |
        echo "THIS IS THE START DIR: $(pwd)" && ls
        cd ..
        echo "THIS IS THE WORKING DIR: $(pwd)" && ls
        git clone https://aur.archlinux.org/yay.git
        ls
        docker pull archlinux:latest
        docker run -v $(pwd)/:/tmp/ --network bridge -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "pacman -Syu --noconfirm && pacman -S --noconfirm base-devel make gcc && cd /tmp/dotFiles && chmod +rx ./install/dependencies.sh && chmod +rx ./install/env.sh && chmod +rx ./install/install.sh && make all"
