name: Validate Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker and run Arch Linux
      uses: actions/checkout@v4
    - run: |
        docker pull archlinux:latest
        docker run -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "pacman -Syu --noconfirm && pacman -S --noconfirm base-devel make gcc && chmod +rx ./install/dependencies.sh && chmod +rx ./install/env.sh && chmod +rx ./install/install.sh && make all"
