name: Syntax Checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Scan code syntax
      uses: actions/checkout@v4

    - name: Install linters and language interpreters
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            bash \
            perl \
            lua5.3 \
            ruby \
            shellcheck \
            ruby-dev
            
          gem install rubocop --user-install
      
    - name: Lint Bash Scripts
      run: |
          find . -type f \( -name "*.sh" -o -exec grep -q -I '^#!.*\bbash\b' {} \; \) -print | xargs realpath | sed 's/^[^/]*//g' | grep '^/home/' | xargs shellcheck 2>&1 | tee /tmp/shellcheck.txt
          if grep -q 'error:' /tmp/shellcheck.txt; then
            echo "Shellcheck found errors!"
            exit 1
          else
            echo "Bash scripts passed!"
          fi
          
    - name: Lint Perl Scripts
      run: find . -type f \( -name "*.pl" -o -name "*.pm" -o -exec grep -q -I '^#!.*\bperl\b' {} \; \) -print | xargs realpath | sed 's/^[^/]*//g' | grep '^/home/' | xargs -I {} perl -c {}

    - name: Lint Lua Scripts
      run: find . -name "*.lua" -print | xargs realpath | sed 's/^[^/]*//g' | grep '^/home/' | xargs luac -p
      
    - name: Lint Ruby Scripts
      run: find . -type f \( -name "*.rb" -o -exec grep -q -I '^#!.*\bruby\b' {} \; \) -print | xargs realpath | sed 's/^[^/]*//g' | grep '^/home/' | xargs /home/runner/.local/share/gem/ruby/3.0.0/bin/rubocop
